spring:
  datasource:
    url: jdbc:mysql://localhost:13306/settlement?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: snow
    password: snow
    hikari:
      maximum-pool-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: trace
#    org.hibernate.orm.jdbc.bind: trace
