spring:
  datasource:
    url: jdbc:mysql://localhost:13306/settlement?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: snow
    password: snow
    hikari:
      maximum-pool-size: 5
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    sql: debug