spring:
  datasource:
    url: jdbc:mysql://localhost:13306/settlement?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: snow
    password: snow
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    sql: debug